name: Acciojob Tests

on:
 push:
    branches: [ "main","master" ]

jobs:
  calling-acciojob-main-action:
    uses: acciojob/acciojob-tests-action/.github/workflows/main-action.yml@main
    secrets: inherit
    // ✅ Use this instead to click the Users navigation:
cy.get('[data-testid="users-nav-link"]').click()

// ✅ Or to click a specific user:
cy.get('[data-testid="user-link-1"]').click() // for user with id=1
cy.get('[data-testid="user-link-2"]').click() // for user with id=2
